packages:
  - "apps/*"
  - "packages/*"
  - "utils/*"

# see: https://github.com/t0bst4r/home-assistant-matter-hub/security/dependabot
overrides:
  "form-data@>=4.0.0 <4.0.4": "4.0.4"
  "vite@<7.0.0": "^7.0.0"
  "tmp@<=0.2.3": "0.2.4"
  "brace-expansion@>=1.0.0 <=1.1.11": "1.1.12"
  "brace-expansion@>=2.0.0 <=2.0.1": "2.0.2"
