name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: nx cache
        uses: actions/cache@v4
        with:
          path: .nx
          key: ${{ runner.os }}-nx

      - run: npm ci
      - run: npm run release -- --yes
      - run: ls -la
      - run: ls -la apps/home-assistant-matter-hub
